config/routes.rb
Rails.application.routes.draw do
  root 'logins#new'

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  resources :companies do
    resources :people
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 100 }

  belongs_to :company_type
  # has_many :people, -> { order 'name' }, dependent: :destroy
  has_many :people, dependent: :destroy
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :company_type_id, null: false
  
  has_many :companies, dependent: :destroy
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  before_save :trim_email
  belongs_to :company

  private
    def trim_email
      self.email = email.strip
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  # validates :password_digest, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :user_is_authenticated?
  before_action :login_required!

  private
    def login_required!
      if !user_is_authenticated?
        flash[:danger] = 'Необходимо выполнить Вход в систему!'
        redirect_to root_path
      end
    end

  def user_is_authenticated?
    !!session[:user_id]
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :init

  def index
  end

  def destroy
    @company.destroy
    flash[:success] = 'Объект был удален.'
    redirect_to companies_path(company_type: @company_type)
  end

  def create
    # FIXME: Duplicates init method
    company_type = CompanyType.find(@company_type)
    @company = company_type.companies.build(company_params)
    if (@company.save)
      flash[:success] = 'Объект успешно сохранен.'
      redirect_to company_path(@company, company_type: @company_type)
    else
      render 'edit'
    end
  end

  def update
    existing_company = params[:id]
    @company = Company.find(existing_company)
    if (@company.update_attributes(company_params))
      flash[:success] = 'Объект успешно сохранен.'
      redirect_to company_path(@company, company_type: @company_type)
    else
      render 'edit'
    end
  end

  def new
    render 'edit'
  end

  def show
    # redirect_to action: 'edit'
    render 'edit'
  end

  def edit
  end

  private
  def init
    existing_company = params[:id]
    if(existing_company)
      @company = Company.find(existing_company)
    else
      @company = Company.new
    end
    @people = @company.people.order(:inactive, :name)
    # FIXME: пользователь может передать любую company_type из GET запроса
    @company_type = params[:company_type] || 1
    @companies = Company.includes(:people, :company_type).where('company_type_id = ?', @company_type).order(:name)
    @company_types = CompanyType.all
  end

  def company_params
    params.require(:company).permit(:name, :fname, :address,
                                    :uraddress, :phone, :contract,
                                    :docsaddress, :invoiceaddress,
                                    :gmocode, :reutercode, :email,
                                    :leid, :comments)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :login_required!

  def new
    @users = User.order(:name)
  end

  def create
    user = User.find(params[:name])
    password = params[:password]
    if(user.authenticate(password))
      session[:user_id] = user.id
      flash[:success] = 'Добро пожаловать!'
      redirect_to companies_path
    else
      flash.now[:danger] = 'Неверный пароль!'
      @users = User.order(:name)
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Вы вышли из системы.'
    redirect_to root_path
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_action :init

  def edit
  end

  def destroy
    @person.destroy
    flash[:success] = 'Объект был удален.'
    redirect_to edit_company_path(params[:company_id], company_type: @company.company_type_id)
  end

  def create
    if(@company.people.build(person_params).save)
      flash[:success] = 'Объект успешно сохранен.'
      redirect_to edit_company_path(params[:company_id], company_type: @company.company_type_id)
    else
      render 'edit'
    end
  end

  def new
    render 'edit'
  end

  def show
    render 'edit'
  end

  def update
    if (@person.update_attributes(person_params))
      flash[:success] = 'Объект успешно сохранен.'
      redirect_to edit_company_path(params[:company_id], company_type: @company.company_type_id)
    else
      render 'edit'
    end
  end

  private
  def person_params
    params.require(:person).permit(:name, :jobtitle, :phone,
                                   :mobphone, :email, :comments, :inactive)

  end

  def init
    @company = Company.find(params[:company_id])
    existing_person = params[:id]
    if (existing_person)
      @person = Person.find(existing_person)
    else
      @person = Person.new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/companies_helper.rb
module CompaniesHelper
  def str_is_email?(str)
    if str.nil?
      return false
    end
    return str.match(/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i)
  end

  def color_active_company(company, id)
    # binding.pry
    if(company.id == id.to_i)
      return 'class=current-company'
    end
    return ''
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/companies/_companies_list.html.erb
<div class="col-xs-2">
  <%= form_tag(companies_path, {method: 'get', id: 'select_type_form'}) do %>
      <%= select_tag 'company_type',
                     options_from_collection_for_select(@company_types, 'id', 'name', params[:company_type]),
                     onchange: "$('#select_type_form').submit();",
                     class: 'form-control' %>
  <% end %>
  <div class="companies-table">
    <table class="table table-bordered table-hover">
      <% @companies.each do |company| %>
          <tr <%= color_active_company(company, params[:id]) %>>
            <td>
              <%= link_to company.name, company_path(company, {company_type: company.company_type}) %>
            </td>
          </tr>
      <% end %>
    </table>
  </div>
  <%= link_to new_company_path(company_type: params[:company_type] || 1),
              method: :get, class: 'btn btn-sm btn-default btn-block' do %>
      <i class="glyphicon glyphicon-plus"></i> Добавить организацию
  <% end %>
</div>

app/views/companies/_company_details.html.erb
<div class="col-xs-10 well">
  <%= form_for @company do |f| %>
      <div class="company-details">
        <div class="row">
          <div class="col-xs-6">
            <%= hidden_field_tag :company_type, @company_type %>
            <div class="form-group">
              <%= f.label :name, 'Наименование:' %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :fname, 'Полное наименование:' %>
              <%= f.text_field :fname, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :address, 'Фактический адрес:' %>
              <%= f.text_field :address, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :uraddress, 'Юридический адрес:' %>
              <%= f.text_field :uraddress, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :contract, 'Договор:' %>
              <%= f.text_field :contract, class: 'form-control', disabled: true %>
            </div>
            <div class="form-group">
              <%= f.label :phone, 'Телефон \ факс:' %>
              <%= f.text_field :phone, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :email, 'Email:' %>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
          </div>
          <div class="col-xs-6">
            <div class="form-group">
              <%= f.label :comments, 'Заметки:' %>
              <%= f.text_area :comments, class: 'form-control text-area-no-width-resize', rows: 23 %>
            </div>
          </div>

        </div>
        <div class="row">
          <div class="col-xs-12">
            <%= render 'people' %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <hr>
            <%= button_tag(type: 'submit', class: 'btn btn-sm btn-primary') do %>
                <i class="glyphicon glyphicon-ok"></i> Сохранить изменения
            <% end %>
            <% if !@company.new_record? %>
                <%= link_to 'Добавить контакт',
                            new_company_person_path(company_id: params[:id], company_type: params[:company_type]),
                            method: :get, class: 'btn btn-sm btn-default' %>
                <div class="pull-right">
                  <%# link_to new_company_person_path(company_id: params[:id]),
                            method: :get, class: 'btn btn-sm btn-danger' do %>
                  <!--<i class="glyphicon glyphicon-remove"></i> Удалить организацию-->
                  <%# end %>
                  <%= link_to @company,
                              data: {confirm: "Этим действием вы также удалите все подчиненные элементы.\n\n" +
                                      "Действительно хотите удалить организацию?"},
                              method: :delete, class: 'btn btn-sm btn-danger' do %>
                      <i class="glyphicon glyphicon-remove"></i> Удалить организацию
                  <% end %>
                </div>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/companies/_company_details_stub.html.erb
<div class="col-xs-10 well">
  <div class="company-details-stub">
    <h1>ВЫБЕРИТЕ ИНТЕРЕСУЮЩУЮ ВАС ОРГАНИЗАЦИЮ</h1>
  </div>
</div>

app/views/companies/_people.html.erb
<div class="people-table">
  <table class="table table-bordered table-hover">
    <tr>
      <th>
        ФИО
      </th>
      <th>
        Гор. Телефон
      </th>
      <th>
        Моб. Телефон
      </th>
      <th>
        E-Mail
      </th>
      <th>
        Должность
      </th>
      <th>
        Доп.Информация
      </th>
    </tr>
    <% @people.each do |person| %>
        <tr class="<%= person.inactive? ? 'inactive': '' %>">
          <td>
            <%= link_to person.name, company_person_path(person, { company_id: @company.id }) %>
          </td>
          <td>
            <%= person.phone %>
          </td>
          <td>
            <%= person.mobphone %>
          </td>
          <td>
            <% if (str_is_email?(person.email)) %>
                <a href="mailto:<%= person.email %>"><%= person.email %></a>
            <% else %>
                <%= person.email %>
            <% end %>
          </td>
          <td>
            <%= person.jobtitle %>
          </td>
          <td>
            <%= person.comments %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/companies/edit.html.erb
<div class="container-fluid">
  <%= render 'layouts/validation_errors', obj: @company %>
  <%= render 'companies_list' %>
  <%= render 'companies/company_details' %>
</div>

app/views/companies/index.html.erb
<div class="container-fluid">
  <%= render 'companies_list' %>
  <%= render 'company_details_stub' %>
</div>

app/views/layouts/_debug.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="row">
      <%# image_tag('handbook.png', size: '32x32', alt: 'Program Icon') %>

      <div class="navbar-header">
        <%= image_tag('handbook.png', alt: 'Program Icon', class: 'pull-left') %>
        <a href="/" class="navbar-brand navbar-brand-custom-font">Handbook <b>NEXT</b></a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_is_authenticated? %>
            <li><a href="/">На главную</a></li>
            <li class="active"><%= link_to 'Организации', companies_path, class: 'active' %></li>
            <li><%= link_to 'Выход', logout_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="messages" id="messages">
  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-xs-offset-3 text-center">
        <% flash.each do |msg_type, msg| %>
            <div class="alert alert-<%= msg_type %>">
              <%= msg %>
              <a class="close" data-dismiss="alert">&#215;</a>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    $(function () {
        $('#messages').delay(2000).fadeOut(1000);
    });
</script>

app/views/layouts/_validation_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="alert alert-danger col-xs-10 col-xs-offset-1">
        <h5>Поля формы заполнены неверно:</h5>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title>Handbook NEXT</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/messages' %>
<%= yield %>
<%= render 'layouts/debug' %>
</body>
</html>

app/views/logins/new.html.erb
<div class="jumbotron dark">
  <hr>
  <div class="container">
    <div class="row">
      <div class="col-md-6 hidden-sm hidden-xs">
        <div class="logo">
        </div>
      </div>
      <!--<div class="col-xs-6 col-xs-offset-3">-->
      <div class="col-md-6 col-md-offset-0 col-xs-6 col-xs-offset-3">

        <%= form_tag '/login' do %>
            <div class="form-group">
              <%= label_tag 'name', 'Имя пользователя:' %>
              <%= select_tag :name,
                             options_from_collection_for_select(@users, 'id', 'name'),
                             class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= label_tag 'password', 'Пароль:' %>
              <%= password_field_tag :password, nil, class: 'form-control' %>
            </div>
            <br>

            <div class="text-center">
              <%= button_tag(type: 'submit', class: 'btn btn-sm btn-primary btn-block') do %>
                  <i class="glyphicon glyphicon-ok"></i> Вход

              <% end %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
</div>

app/views/people/edit.html.erb
<div class="container well">

  <%= render 'layouts/validation_errors', obj: @person %>

  <%= form_for([@company, @person]) do |f| %>
      <%# form_for @person, url: {action: 'update'} do |f| %>
      <div class="row">
        <div class="col-xs-6">
          <div class="form-group">
            <%= f.label :name, 'ФИО:' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :jobtitle, 'Должность:' %>
            <%= f.text_field :jobtitle, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :phone, 'Гор. Телефон:' %>
            <%= f.text_field :phone, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :mobphone, 'Моб. Телефон:' %>
            <%= f.text_field :mobphone, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, 'E-Mail:' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="checkbox">
            <%= f.label :inactive do %>
                <%= f.check_box :inactive %> Архивный элемент
            <% end %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <%= f.label :comments, 'Доп. Информация:' %>
            <%= f.text_area :comments, class: 'form-control text-area-no-width-resize', rows: 23 %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <hr>
          <%= button_tag(type: 'submit', class: 'btn btn-sm btn-primary') do %>
              <i class="glyphicon glyphicon-ok"></i> Сохранить изменения
          <% end %>
          <%= link_to 'Отмена', company_path(@company, company_type: @company.company_type_id), class: 'btn btn-sm btn-default' %>
          <div class="pull-right">
            <%= link_to [@company, @person], data: {confirm: 'Действительно хотите удалить элемент?'},
                        method: :delete, class: 'btn btn-sm btn-danger' do %>
                <i class="glyphicon glyphicon-remove"></i> Удалить контакт
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div>